Music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.index, name='index'),
    # /music/<int:album_id>/create_song
    path('<pk>/create_song/', views.create_song, name='create_song'),
    # /music/<int:album_id>/
    path('<int:album_id>/', views.detail, name='detail'),
    # /music/logout_user
    path('logout_user/', views.logout_user, name='logout_user'),
    # /music/create_album
    path('create_album/', views.create_album, name='create_album'),
    # /music/<int:album_id>/delete_song/<int:song_id>/
    path('<int:album_id>/delete_song/<int:song_id>/', views.delete_song, name='delete_song'),
    # /music/<int:album_id>/delete_album/
    path('<int:album_id>/delete_album/', views.delete_album, name='delete_album'),
    # /music/<int:album_id>/favorite_album/
    path('<int:album_id>/favorite_album/', views.favorite_album, name='favorite_album'),
    # /music/songs/--
    re_path(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    # /music/<song_id>/favorite/
    re_path(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

website/urls.py
import sys
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
import Music.views as views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('Music.urls')),
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    album_genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    album_year = models.DateField(null=True)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.artist + "-" + self.album_title


class Songs(models.Model):
    albums = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    song_genre = models.CharField(max_length=100)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

Music/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Album, Songs

class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'album_genre', 'album_logo', 'album_year']


class SongForm(forms.ModelForm):
    
    class Meta:
        model = Songs
        fields = ['song_title', 'audio_file', 'song_genre']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import AlbumForm, SongForm, UserForm
from .models import Album, Songs


AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg', 'flac', 'acc', 'm4a']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_album(request):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            file_type = album.album_logo.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                response = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_album.html', response)
            album.save()
            return render(request, 'music/detail.html', {'album': album})
        response = {
            "form": form,
        }
        return render(request, 'music/create_album.html', response)



def create_song(request, pk):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=pk)
    if form.is_valid():
        album_songs = album.songs_set.all()
        for s in album_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                response = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/create_song.html', response)
        song = form.save(commit=False)
        song.albums = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            response = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, Flac, ACC, or OGG',
            }
            return render(request, 'music/create_song.html', response)

        song.save()
        return render(request, 'music/detail.html', {'album': album})
    response = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/create_song.html', response)



def delete_album(request, album_id):
    album = Album.objects.get(pk = album_id)
    album.delete()
    albums = Album.objects.filter(user =request.user)
    return render (request, 'music/index.html', {'albums':albums})



def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Songs.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})



def detail(request, album_id):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'music/detail.html', {'album': album, 'user': user})



def favorite(request, song_id):
    song = get_object_or_404(Songs, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Songs.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})



def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})



def index(request):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        albums = Album.objects.filter(user=request.user)
        song_results = Songs.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            return render(request, 'music/index.html', {
                'albums': albums,
                'songs': song_results,
            })
        else:
            return render(request, 'music/index.html', {'albums': albums})



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    response = {
        "form": form,
    }
    return render(request, 'music/login.html', response)



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')



def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
    response = {
        "form": form,
    }
    return render(request, 'music/register.html', response)



def songs(request, filter_by):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.songs_set.all():
                    song_ids.append(song.pk)
            users_songs = Songs.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'songs_list': users_songs,
            'filter_by': filter_by,
        })

Music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Air Music</title>
    {% load staticfiles %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href= "{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'music/style.css' %}" rel="stylesheet">
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src= "{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Main Js for Project -->
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>


</head>



    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="{% url "music:index" %}" target="_blank">
                    <img src="https://img.icons8.com/clouds/100/000000/music.png" width="30" height="30" class="d-inline-block align-top" alt="" >
                    <strong class="red-text">Air Music</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link waves-effect" href="{% url "music:index" %}">
                                <img src="{% static 'music/images/iconmonstr-disc-5-24 (1).png' %}" class="d-inline-block align-top" alt="">&nbsp
                                Albums
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url "music:songs" 'all' %}" target="_blank">
                                <img src="{% static 'music/images/iconmonstr-disc-4-24 (1).png' %}" class="d-inline-block align-top" alt="">&nbsp
                                 Songs
                             </a>
                        </li>
                        <!--<li class="nav-item">
                            a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank">Free download</a>
                        </li> -->

                        <form class="form-inline" role="search" method="get" action="{% url 'music:index' %}">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-transparent">
                                        <img src="{% static 'music/images/iconmonstr-magnifier-4-24.png' %}" class="d-inline-block align-top" alt="">
                                    </span>
                                </div>
                                <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1" name="q" value="{{ request.GET.q }} ">
                            </div>
                        </form>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        <li class="nav-item">
                            <a href="{% url 'music:create_album' %}" class="nav-link waves-effect" target="_blank">
                                <img src="{% static 'music/images/iconmonstr-plus-6-24.png' %}" class="d-inline-block align-top" alt="">&nbsp
                                Add Album
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                            <li class="nav-item">
                                <a href="{% url 'music:logout_user' %}" class="nav-link waves-effect" target="_blank">
                                    <img src="{% static 'music/images/log-out-9.svg' %}" class="d-inline-block align-top" alt=""></span>&nbsp
                                    Sign Out
                                </a>
                            </li>
                        <li class="nav-item">
                            <a href="https://github.com/Andyphied" class="nav-link border border-light rounded waves-effect" target="_blank">
                                <i class="fab fa-github mr-2"></i>Andyphied GitHub
                            </a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>

    {% block body %}
    {% endblock %}

   <!--Footer-->
    <footer class="footer text-center font-small mdb-color lighten-3 mt-4 wow fadeIn">

        <!--Call to action-->
        <div class="pt-4">
            <a class="btn btn-outline-white" href="#/" target="_blank" role="button">Download Mobile App
                <i class="fas fa-download ml-2"></i>
            </a>
            <a class="btn btn-outline-white" href="#" target="_blank" role="button">Start free trial
                <i class="fas fa-handshake ml-2"></i>
            </a>
        </div>
        <!--/.Call to action-->

        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="https://www.facebook.com/Andyphied" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="https://twitter.com/Andyphied" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="https://dribbble.com/Andyphied" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="https://pinterest.com/Andyphied" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="https://github.com/Andyphied/bootstrap-material-design" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="http://codepen.io/Andyphied/" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3 black-text">
            © 2020 Copyright:
            <a target="_blank" class= 'red-text'> Air Music </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    

</html>

Music/templates/music/create_song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
{% extends 'music/base.html' %}
{% load staticfiles %}

    {% block body %}


        <!--Main layout-->
        <main class="mt-5 pt-5">
            <div class="container">

                <!--Section: Jumbotron-->
                <section class="card wow fadeIn" style="background-image: url({% static 'music/images/crowd-1056764_1920.jpg' %});">

                    <!-- Content -->
                    <div class="card-body text-white text-center py-5 px-5 my-5">

                        <h1 class="mb-4">
                            <strong>Expand The Space Available to You</strong>
                        </h1>
                        <p>
                            <strong>Be free to Add has many song as you want</strong>
                        </p>
                        <p class="mb-4">
                            <strong>Loved by over 500 000 users using the paid version. Create your own, musical santuary on the cloud.</strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Add Additional Drives
                            <i class="fas fa-graduation-cap ml-2"></i>
                        </a>

                    </div>
                    <!-- Content -->
                </section>
                <!--Section: Jumbotron-->

                <!--Grid column-->
                <div class="row mb-4 wow fadeIn">
                        <div class="col-sm-12" >
                            <h3 class="text-white">{{ user.username }}'s Albums</h3>
                        </div>
                        {% if albums %}
                            {% for album in albums %}
                                <div class="col-lg-4 col-md-12 mb-4">
                                    
                                    <div class="card">
                                        
                                        <div class="view overlay">
                                            <img src="{{album.album_logo}}" class="card-img-top" alt="Not Displayed">
                                            <a href="{% url 'music:detail' album.id %}" target="_blank">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>

                                        <!--Card content-->
                                        <div class="card-body">
                                            <!--Title-->
                                            <h2 class="card-title">{{ album.album_title }}</h2>
                                            <!--Text-->
                                            <h4 class="card-text">{{ album.artist }}</h4>

                                            <!-- View Details -->
                                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                            <!-- Delete Album -->
                                            <form action="{% url 'music:delete_album' album.id %}" method="post" style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                                <button type="submit" class="btn btn-default btn-sm">
                                                    <span class="fa fa-trash"></span>
                                                </button>
                                            </form>

                                            <!-- Favorite Album -->
                                            <a href="{% url 'music:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                                <span class="fa fa-star {% if album.is_favorite %}active{% endif %}"></span>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                            {% endfor %}
                        {% else %}
                            <div class="col-sm-12">
                                <br>
                                    <a href="{% url 'music:create_album' %}">
                                    <button type="button" class="btn btn-success">
                                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                                    </button>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <!--Grid column-->

                    <!-- If user searches and there are songs -->
                    {% if songs %}
                        <div class="row">
                            <div class="col-sm-12">
                                <h3>Songs</h3>
                            </div>
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Song Title</th>
                                                    <th>Artist</th>
                                                    <th>Audio File</th>
                                                    <th>Album</th>
                                                    <th>Favorite</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for song in songs %}
                                                    <tr>
                                                        <td>{{ song.song_title }}</td>
                                                        <td>{{ song.album.artist }}</td>
                                                        <td>
                                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                                <button type="button" class="btn btn-success btn-xs">
                                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                                </button>
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a href="{% url 'music:detail' song.album.id %}">
                                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                                            </a>
                                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                                        </td>
                                                        <td>
                                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                        <!--Grid column-->

                        

                    <!--Pagination-->
                    <nav class="d-flex justify-content-center wow fadeIn">
                        <ul class="pagination pg-blue">

                            <!--Arrow left-->
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>

                            <li class="page-item active">
                                <a class="page-link" href="#">1
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">4</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">5</a>
                            </li>

                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <!--Pagination-->

                </section>
                <!--Section: Cards-->

            </div>
        </main>
        <!--Main layout-->
    
    {% endblock %}       

</html>